// Code generated by MockGen. DO NOT EDIT.
// Source: user_service.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	models "github.com/archMqq/book-helper/internal/models"
	gomock "github.com/golang/mock/gomock"
)

// MockUserRepository is a mock of UserRepository interface.
type MockUserRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUserRepositoryMockRecorder
}

// MockUserRepositoryMockRecorder is the mock recorder for MockUserRepository.
type MockUserRepositoryMockRecorder struct {
	mock *MockUserRepository
}

// NewMockUserRepository creates a new mock instance.
func NewMockUserRepository(ctrl *gomock.Controller) *MockUserRepository {
	mock := &MockUserRepository{ctrl: ctrl}
	mock.recorder = &MockUserRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserRepository) EXPECT() *MockUserRepositoryMockRecorder {
	return m.recorder
}

// GetPreferences mocks base method.
func (m *MockUserRepository) GetPreferences(arg0 context.Context, arg1 int64) (*models.Preferences, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPreferences", arg0, arg1)
	ret0, _ := ret[0].(*models.Preferences)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPreferences indicates an expected call of GetPreferences.
func (mr *MockUserRepositoryMockRecorder) GetPreferences(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPreferences", reflect.TypeOf((*MockUserRepository)(nil).GetPreferences), arg0, arg1)
}

// Register mocks base method.
func (m *MockUserRepository) Register(arg0 context.Context, arg1 int64, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Register", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// Register indicates an expected call of Register.
func (mr *MockUserRepositoryMockRecorder) Register(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*MockUserRepository)(nil).Register), arg0, arg1, arg2)
}

// SaveFavoriteAuthors mocks base method.
func (m *MockUserRepository) SaveFavoriteAuthors(arg0 context.Context, arg1 int64, arg2 []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveFavoriteAuthors", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveFavoriteAuthors indicates an expected call of SaveFavoriteAuthors.
func (mr *MockUserRepositoryMockRecorder) SaveFavoriteAuthors(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveFavoriteAuthors", reflect.TypeOf((*MockUserRepository)(nil).SaveFavoriteAuthors), arg0, arg1, arg2)
}

// SaveFavoriteGenres mocks base method.
func (m *MockUserRepository) SaveFavoriteGenres(arg0 context.Context, arg1 int64, arg2 []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveFavoriteGenres", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveFavoriteGenres indicates an expected call of SaveFavoriteGenres.
func (mr *MockUserRepositoryMockRecorder) SaveFavoriteGenres(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveFavoriteGenres", reflect.TypeOf((*MockUserRepository)(nil).SaveFavoriteGenres), arg0, arg1, arg2)
}
