// Code generated by MockGen. DO NOT EDIT.
// Source: service.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockGPTClient is a mock of GPTClient interface.
type MockGPTClient struct {
	ctrl     *gomock.Controller
	recorder *MockGPTClientMockRecorder
}

// MockGPTClientMockRecorder is the mock recorder for MockGPTClient.
type MockGPTClientMockRecorder struct {
	mock *MockGPTClient
}

// NewMockGPTClient creates a new mock instance.
func NewMockGPTClient(ctrl *gomock.Controller) *MockGPTClient {
	mock := &MockGPTClient{ctrl: ctrl}
	mock.recorder = &MockGPTClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGPTClient) EXPECT() *MockGPTClientMockRecorder {
	return m.recorder
}

// AskForNewBooks mocks base method.
func (m *MockGPTClient) AskForNewBooks(arg0 context.Context, arg1 string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AskForNewBooks", arg0, arg1)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AskForNewBooks indicates an expected call of AskForNewBooks.
func (mr *MockGPTClientMockRecorder) AskForNewBooks(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AskForNewBooks", reflect.TypeOf((*MockGPTClient)(nil).AskForNewBooks), arg0, arg1)
}
